### ISSUE TITLE
No demo and example

### ISSUE THREAD

**Issue by xuxichen** [RyanRong/RongICLOUD-IMLIB-React-Native#2]
您好，非常感谢你的开源贡献，但我发现你这个开源项目中没有demo或者案例，不知道您是否会在后期添加？以便于其他开发者更好更快的上手。

**Comment by RyanRong** [comment]
不好意思，短期之内没有维护的打算了，已经从这个项目中离职。

Chad Xu <notifications@github.com> 于 2018年8月16日周四 上午11:19写道：
